services:
    workwize-store-app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: workwize-store/app
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_SESSION: '${XDEBUG_SESSION:-1}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
            PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=workwize-store.site}'
        networks:
            - workwize-store
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - .:/var/www/html
        depends_on:
            workwize-store-mysql:
                condition: service_healthy
            workwize-store-redis:
                condition: service_started

    workwize-store-mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - '${DB_FORWARD_PORT:-3306}:3306'
        networks:
            - workwize-store
        volumes:
            - ./docker/db:/var/lib/db
            - workwize-store-mysql:/var/lib/mysql
        healthcheck:
            test: [ 'CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}' ]
            retries: 3
            timeout: 5s

    workwize-store-redis:
        image: 'redis:alpine'
        ports:
            - '${REDIS_FORWARD_PORT:-6379}:6379'
        networks:
            - workwize-store
        volumes:
            - 'workwize-store-redis:/data'
        healthcheck:
            test: [ 'CMD', 'redis-cli', 'ping' ]
            retries: 3
            timeout: 5s

    workwize-store-nginx:
        image: nginx:stable-alpine
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - workwize-store
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf:/etc/nginx/conf.d
        depends_on:
            - workwize-store-app

    workwize-frontend:
        user: 'node'
        build:
            context: ./docker
            dockerfile: Dockerfile-frontend
        image: workwize/frontend
        ports:
            - '${VITE_PORT:-5173}:5173'
        networks:
            - workwize-store
        volumes:
            - .:/var/www/html

networks:
    workwize-store:
        driver: bridge

volumes:
    workwize-store-mysql:
        driver: local
    workwize-store-redis:
        driver: local
