#!/usr/bin/env bash

mysql --user=root --password="${MYSQL_PASSWORD}" <<-EOSQL
    DROP DATABASE IF EXISTS ${MYSQL_DATABASE};
    DROP DATABASE IF EXISTS ${MYSQL_DATABASE}_test;

    CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
    CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}_test;

    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_PASSWORD}';
EOSQL
